from typing import Literal
import dspy
import os 

lm = dspy.LM('azure/gpt-4o-mini-global', api_key = os.getenv('AZURE_OPENAI_API_KEY'), api_base=os.getenv('AZURE_API_BASE'), api_version='2024-12-01-preview')
dspy.configure(lm=lm)

ollama_base_url = "http://localhost:11434"
lm_student = dspy.LM('ollama_chat/llama3.1:8b', api_base=ollama_base_url, api_key='')
dspy.configure(lm=lm_student)

class Categorise(dspy.Signature):
    """
    Classify the given document text into one of the following accounting account names.
    """

    document_text: str = dspy.InputField(desc="The full text content of the document to be classified.")
    account_type: Literal[
        'Accountancy Fees',
        'Accounting Fees',
        'Accounts Payable',
        'Accounts Receivable',
        'Accrued and Deferred Items',
        'Adjustments to Retained Earnings',
        'Advertising',
        'Amortisation',
        'Assets',
        'ATO Integrated Client Account',
        'Bad Debts Written Off',
        'Balance at Beginning of Year',
        'Bank charges',
        'Bank Fees',
        'Bank Revaluations',
        'Bookkeeping',
        'Borrowing Costs',
        'Borrowing Expenses',
        'Borrowings',
        'Capital',
        'Capital Lease',
        'Cash and Cash Equivalents',
        'Cash on Hand',
        'Cleaning',
        'Cleaning & Laundry',
        'Closing Stock',
        'Closing WIP',
        'Commissions Received',
        'Computer Equipment',
        'Computer Expenses',
        'Consultancy Fees',
        'Consulting & Accounting',
        'Cost of Goods Sold',
        'Cost of Sales',
        'Credit Cards and Overdrafts',
        'Current Assets',
        'Current Earnings',
        'Current Liabilities',
        'Current Tax Assets',
        'Current Tax Liabilities',
        'Current Year Earnings',
        'Deferred Tax Assets',
        'Deferred Tax Liabilities',
        'Depreciation',
        'Depreciation and Amortisation',
        'Discontinued Operations',
        'Distributions',
        'Dividends Received',
        'Donations',
        'Drawings',
        'Electricity',
        'Electricity & Gas',
        'Employee Contribution',
        'Entertainment',
        'Equity',
        'Expenses',
        'Filing Fees',
        'Fines & Penalties',
        'Foreign Currency Gains and Losses',
        'Formation Costs',
        'Formation Expenses',
        'Freight & Cartage',
        'Freight & Courier',
        'Fringe Benefits Tax',
        'Fuel & Oil',
        'General Expenses',
        'Goodwill',
        'GST',
        'GST Payable',
        'Hire of Plant & Equipment',
        'Historical Adjustment',
        'Income',
        'Income Tax',
        'Income Tax expense',
        'Income Tax Payable',
        'Insurance',
        'Intangibles',
        'Interest',
        'Interest Expense',
        'Interest Income',
        'Interest Paid',
        'Interest Received',
        'Internet',
        'Inventories',
        'Inventory',
        'Investments',
        'Items that may be reclassified subsequently to Profit or Loss',
        'Items that will not be reclassified subsequently to Profit or Loss',
        'Land at Cost',
        'Land Tax',
        'Legal expenses',
        'Legal fees',
        'Less Accumulated Depreciation',
        'Less Accumulated Depreciation on Computer Equipment',
        'Less Accumulated Depreciation on Motor Vehicles',
        'Less Accumulated Depreciation on Office Equipment',
        'Less Accumulated Depreciation on Plant & Equipment',
        'Less: Accumulated Depreciation',
        'Liabilities',
        'Light & Power & Heating',
        'Loan',
        'Merchant Fees',
        'Minority Interest',
        'Motor Vehicle Expenses',
        'Motor Vehicles',
        'Movements to Opening Retained Earnings',
        'Non Current Assets',
        'Non Current Liabilities',
        'Office Equipment',
        'Office Expenses',
        'Opening Balance',
        'Opening Stock',
        'Opening WIP',
        'Other',
        'Other Comprehensive Income',
        'Other creditors',
        'Other Current Assets',
        'Other Current Liabilities',
        'Other Expenses',
        'Other Financial Assets',
        'Other Income',
        'Other Liabilities',
        'Other Non Current Assets',
        'Other Operating Income',
        'Other Revenue',
        'Owner A Drawings',
        'Owner A Funds Introduced',
        'Owner A Share Capital',
        'PAYG Withholdings Payable',
        'Payroll Liabilities',
        'Payroll Tax',
        'Petty Cash',
        'Plant & Equipment',
        'Postage',
        'Prepayments',
        'Printing & Stationery',
        'Prior Period Losses Applied',
        'Professional fees',
        'Property, Plant and Equipment',
        'Protective clothing',
        'Provision for Annual Leave',
        'Provision For Doubtful Debts',
        'Provision for Income Tax',
        'Provision for Long Service Leave',
        'Provisions',
        'Purchases',
        'Rates',
        'Realised Currency Gains',
        'Related Party Loans',
        'Rent',
        'Rent Received',
        'Rental Income',
        'Repairs & Maintenance',
        'Repairs and Maintenance',
        'Research & Development',
        'Reserves',
        'Retained Earnings',
        'Revenue',
        'Rounding',
        'Sales',
        'Security',
        'Settled Sum',
        'Settlement Sum',
        'Share of Profit',
        'Shares in Listed Companies',
        'Staff Amenities',
        'Staff Training',
        'Stamp Duty',
        'Stock on Hand',
        'Subcontractors',
        'Subscriptions',
        'Subscriptions & Memberships',
        'Sundry Creditors',
        'Sundry Debtors',
        'Sundry Expenses',
        'Superannuation',
        'Superannuation Payable',
        'Suspense',
        'Telephone',
        'Telephone & Internet',
        'Tracking Transfers',
        'Trade and Other Payables',
        'Trade and Other Receivables',
        'Trade creditors',
        'Trade Debtors',
        'Transfers to or from Reserves',
        'Travel - International',
        'Travel - National',
        'Trust Distributions Received',
        'Unallocated',
        'Uniforms',
        'Unpaid Expense Claims',
        'Unrealised Currency Gains',
        'Wages',
        'Wages & Salaries',
        'Wages and Salaries',
        'Wages Payable',
        'Wages Payable - Payroll',
        'Waste Disposal',
        'Work in progress'
    ] = dspy.OutputField(desc="The predicted accounting account for the document.")

classify = dspy.ChainOfThought(Categorise)
